import type { ReactNode } from 'react'
import { useMemo, useState } from 'react'
import { format } from 'date-fns'
import { ArrowRight, CalendarIcon, ClipboardList, Mail, Sparkles } from 'lucide-react'

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Progress } from '@/components/ui/progress'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Calendar } from '@/components/ui/calendar'

type BudgetRange = string

type ProjectType = string

type Timeline =
  | 'ASAP'
  | '2–4 weeks'
  | '1–2 months'
  | '3–6 months'
  | '6+ months'
  | 'Not sure'

type WizardData = {
  name: string
  email: string
  company: string
  industry: string
  industryOther: string
  projectType: ProjectType
  projectTypeOther: string
  description: string
  timeline: Timeline | ''
  goLiveDate: string
  currency: CurrencyCode | ''
  budget: BudgetRange | ''
  hasBranding: boolean
  hasContent: boolean
  hasDomain: boolean
  needsDesign: boolean
  notes: string
}

const STORAGE_KEY = 'devcon1:start-project'

type CurrencyCode = 'ZAR' | 'USD' | 'ZMW' | 'GBP' | 'EUR'

const CURRENCIES: ReadonlyArray<{
  code: CurrencyCode
  label: string
  ranges: readonly string[]
}> = [
  {
    code: 'ZAR',
    label: 'Rands (ZAR)',
    ranges: ['Under R10k', 'R10k–R25k', 'R25k–R50k', 'R50k–R100k', 'R100k+', 'Not sure'],
  },
  {
    code: 'USD',
    label: 'US Dollar (USD)',
    ranges: ['Under $1k', '$1k–$5k', '$5k–$10k', '$10k–$25k', '$25k+', 'Not sure'],
  },
  {
    code: 'ZMW',
    label: 'Kwacha (ZMW)',
    ranges: ['Under K5k', 'K5k–K25k', 'K25k–K50k', 'K50k–K150k', 'K150k+', 'Not sure'],
  },
  {
    code: 'GBP',
    label: 'Pound Sterling (GBP)',
    ranges: ['Under £1k', '£1k–£5k', '£5k–£10k', '£10k–£25k', '£25k+', 'Not sure'],
  },
  {
    code: 'EUR',
    label: 'Euro (EUR)',
    ranges: ['Under €1k', '€1k–€5k', '€5k–€10k', '€10k–€25k', '€25k+', 'Not sure'],
  },
] as const

const INDUSTRIES = [
  'Aerospace & Defense',
  'Agriculture',
  'Automotive',
  'Banking',
  'Biotech',
  'Construction',
  'Consulting',
  'Consumer Goods',
  'Cybersecurity',
  'Data & Analytics',
  'E-commerce',
  'Education',
  'Energy & Utilities',
  'Engineering',
  'Entertainment & Media',
  'Environmental Services',
  'Event Services',
  'Financial Services',
  'Fitness & Wellness',
  'Food & Beverage',
  'Government',
  'Healthcare',
  'Hospitality & Tourism',
  'Insurance',
  'Legal',
  'Logistics & Supply Chain',
  'Manufacturing',
  'Mining',
  'Nonprofit',
  'Professional Services',
  'PropTech / Real Estate',
  'Retail',
  'SaaS / Software',
  'Telecommunications',
  'Transportation',
  'Venture / Startup',
  'Other',
] as const

const PROJECT_TYPES = [
  'Marketing website (service business)',
  'Landing page',
  'Portfolio / personal site',
  'Blog / content site',
  'CMS-backed website',
  'E-commerce',
  'Marketplace',
  'Booking / appointments',
  'Membership / subscriptions',
  'SaaS product',
  'Web app (custom)',
  'Internal tool / dashboard',
  'Admin portal',
  'CRM / lead management',
  'ERP / operations tool',
  'Analytics / reporting',
  'Data pipeline / ETL',
  'API / integration',
  'Automation / workflows',
  'DevOps / CI/CD / infra',
  'Observability / monitoring',
  'Security review / hardening',
  'Mobile app',
  'Desktop app',
  'AI integration / chatbot',
  'Other',
] as const

function buildSummary(data: WizardData) {
  const resolvedIndustry = data.industry === 'Other' ? (data.industryOther || 'Other') : data.industry
  const resolvedProjectType = data.projectType === 'Other' ? (data.projectTypeOther || 'Other') : data.projectType
  const goLiveLine = data.goLiveDate ? `Desired go-live date: ${data.goLiveDate}` : `Desired timeline: ${data.timeline || '—'}`
  const assets = [
    data.hasBranding ? 'Branding' : null,
    data.hasContent ? 'Content' : null,
    data.hasDomain ? 'Domain' : null,
    data.needsDesign ? 'Needs design support' : null,
  ].filter(Boolean)

  return [
    'Project intake (generated by wizard)',
    '',
    `Name: ${data.name || '—'}`,
    `Email: ${data.email || '—'}`,
    `Business / Company: ${data.company || '—'}`,
    `Industry: ${resolvedIndustry || '—'}`,
    `Project type: ${resolvedProjectType || '—'}`,
    goLiveLine,
    `Currency: ${data.currency ? CURRENCIES.find((c) => c.code === data.currency)?.label || data.currency : '—'}`,
    `Budget: ${data.budget || '—'}`,
    `Assets: ${assets.length ? assets.join(', ') : '—'}`,
    '',
    'What needs to be built / help needed:',
    data.description?.trim() ? data.description.trim() : '—',
    '',
    'Additional notes:',
    data.notes?.trim() ? data.notes.trim() : '—',
  ].join('\n')
}

function saveToStorage(data: WizardData) {
  const payload = {
    ...data,
    summary: buildSummary(data),
    createdAt: new Date().toISOString(),
  }
  localStorage.setItem(STORAGE_KEY, JSON.stringify(payload))
  return payload
}

export function StartProjectDialog({
  trigger,
  defaultToWizard = false,
}: {
  trigger: ReactNode
  defaultToWizard?: boolean
}) {
  const [open, setOpen] = useState(false)
  const [mode, setMode] = useState<'choice' | 'wizard'>(defaultToWizard ? 'wizard' : 'choice')
  const [step, setStep] = useState(0)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [confirmAction, setConfirmAction] = useState<'skip' | 'back-to-choice'>('skip')
  const [data, setData] = useState<WizardData>({
    name: '',
    email: '',
    company: '',
    industry: '',
    industryOther: '',
    projectType: '',
    projectTypeOther: '',
    description: '',
    timeline: '',
    goLiveDate: '',
    currency: '',
    budget: '',
    hasBranding: false,
    hasContent: false,
    hasDomain: false,
    needsDesign: false,
    notes: '',
  })

  const steps = useMemo(
    () => [
      { title: 'Basics' },
      { title: 'Business' },
      { title: 'Project' },
      { title: 'Timeline & budget' },
      { title: 'Assets' },
      { title: 'Review' },
    ],
    [],
  )

  const percent = useMemo(() => Math.round(((step + 1) / steps.length) * 100), [step, steps.length])
  const summary = useMemo(() => buildSummary(data), [data])
  const submitMailtoHref = useMemo(() => {
    const subject = encodeURIComponent(`Project brief${data.company ? ` — ${data.company}` : ''}`)
    const body = encodeURIComponent(summary)
    return `mailto:systems.devconone@gmail.com?subject=${subject}&body=${body}`
  }, [data.company, summary])

  const canNext = useMemo(() => {
    if (step === 0) return Boolean(data.name.trim()) && Boolean(data.email.trim())
    if (step === 1) {
      if (!data.company.trim()) return false
      if (!data.industry.trim()) return false
      if (data.industry === 'Other' && !data.industryOther.trim()) return false
      return true
    }
    if (step === 2) {
      if (!data.projectType) return false
      if (data.projectType === 'Other' && !data.projectTypeOther.trim()) return false
      return Boolean(data.description.trim())
    }
    if (step === 3) return Boolean(data.timeline) && Boolean(data.currency) && Boolean(data.budget)
    return true
  }, [data, step])

  function resetWizard() {
    setMode(defaultToWizard ? 'wizard' : 'choice')
    setStep(0)
    setData({
      name: '',
      email: '',
      company: '',
      industry: '',
      industryOther: '',
      projectType: '',
      projectTypeOther: '',
      description: '',
      timeline: '',
      goLiveDate: '',
      currency: '',
      budget: '',
      hasBranding: false,
      hasContent: false,
      hasDomain: false,
      needsDesign: false,
      notes: '',
    })
  }

  function goContact(withPrefill: boolean) {
    if (withPrefill) saveToStorage(data)
    window.location.href = '/contact'
  }

  async function copy(text: string) {
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      // ignore
    }
  }

  return (
    <>
      <Dialog
        open={open}
        onOpenChange={(next) => {
          setOpen(next)
          if (!next) resetWizard()
        }}
      >
        <DialogTrigger asChild>{trigger}</DialogTrigger>
        <DialogContent className="z-[60] max-h-[85vh] overflow-y-auto sm:max-w-2xl">
        {mode === 'choice' ? (
          <>
            <DialogHeader>
              <DialogTitle>Start a project</DialogTitle>
              <DialogDescription>Choose the fastest way to get started.</DialogDescription>
            </DialogHeader>

            <div className="grid gap-3 md:grid-cols-2">
              <button
                type="button"
                onClick={() => goContact(false)}
                className="rounded-xl border border-border/60 bg-background/40 p-5 text-left transition-colors hover:border-emerald-500/20 hover:bg-muted/40"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-sm font-semibold">Use the contact page</p>
                    <p className="mt-1 text-sm text-muted-foreground">Write what you need help with and send it.</p>
                  </div>
                  <span className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-emerald-500/15 bg-emerald-500/10">
                    <Mail className="h-4 w-4 text-emerald-400" />
                  </span>
                </div>
              </button>

              <button
                type="button"
                onClick={() => setMode('wizard')}
                className="rounded-xl border border-border/60 bg-background/40 p-5 text-left transition-colors hover:border-emerald-500/20 hover:bg-muted/40"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-sm font-semibold">Follow a guided wizard</p>
                    <p className="mt-1 text-sm text-muted-foreground">Answer a few questions and we’ll format it for you.</p>
                  </div>
                  <span className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-emerald-500/15 bg-emerald-500/10">
                    <Sparkles className="h-4 w-4 text-emerald-400" />
                  </span>
                </div>
              </button>
            </div>
          </>
        ) : (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center justify-between gap-3">
                <span className="inline-flex items-center gap-2">
                  <ClipboardList className="h-5 w-5 text-emerald-400" />
                  Project wizard
                </span>
                <span className="text-xs text-muted-foreground">
                  Step {step + 1} of {steps.length}
                </span>
              </DialogTitle>
              <DialogDescription>{steps[step]?.title}</DialogDescription>
            </DialogHeader>

            <Progress value={percent} className="h-2" />

            {step === 0 && (
              <div className="grid gap-4 md:grid-cols-2">
                <div className="grid gap-2">
                  <Label htmlFor="sp-name">Name</Label>
                  <Input
                    id="sp-name"
                    value={data.name}
                    onChange={(e) => setData((prev) => ({ ...prev, name: e.target.value }))}
                    placeholder="Your name"
                    autoComplete="name"
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="sp-email">Email</Label>
                  <Input
                    id="sp-email"
                    value={data.email}
                    onChange={(e) => setData((prev) => ({ ...prev, email: e.target.value }))}
                    placeholder="you@company.com"
                    autoComplete="email"
                    inputMode="email"
                  />
                </div>
              </div>
            )}

            {step === 1 && (
              <div className="grid gap-4 md:grid-cols-2">
                <div className="grid gap-2">
                  <Label htmlFor="sp-company">Business / Company name</Label>
                  <Input
                    id="sp-company"
                    value={data.company}
                    onChange={(e) => setData((prev) => ({ ...prev, company: e.target.value }))}
                    placeholder="Company name"
                  />
                </div>
                <div className="grid gap-2">
                  <Label>Industry</Label>
                  <Select value={data.industry} onValueChange={(value) => setData((prev) => ({ ...prev, industry: value }))}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select an industry" />
                    </SelectTrigger>
                    <SelectContent className="z-[70] max-h-80">
                      {INDUSTRIES.map((value) => (
                        <SelectItem key={value} value={value}>
                          {value}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                {data.industry === 'Other' ? (
                  <div className="grid gap-2 md:col-span-2">
                    <Label htmlFor="sp-industry-other">Industry (other)</Label>
                    <Input
                      id="sp-industry-other"
                      value={data.industryOther}
                      onChange={(e) => setData((prev) => ({ ...prev, industryOther: e.target.value }))}
                      placeholder="Type your industry"
                    />
                  </div>
                ) : null}
              </div>
            )}

            {step === 2 && (
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <Label>What do you want built?</Label>
                  <Select
                    value={data.projectType}
                    onValueChange={(value) => setData((prev) => ({ ...prev, projectType: value }))}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select a project type" />
                    </SelectTrigger>
                    <SelectContent className="z-[70] max-h-80">
                      {PROJECT_TYPES.map((value) => (
                        <SelectItem key={value} value={value}>
                          {value}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {data.projectType === 'Other' && (
                  <div className="grid gap-2">
                    <Label htmlFor="sp-project-other">Describe the type</Label>
                    <Input
                      id="sp-project-other"
                      value={data.projectTypeOther}
                      onChange={(e) => setData((prev) => ({ ...prev, projectTypeOther: e.target.value }))}
                      placeholder="e.g. mobile app, landing page, portal"
                    />
                  </div>
                )}

                <div className="grid gap-2">
                  <Label htmlFor="sp-description">What do you need help with?</Label>
                  <Textarea
                    id="sp-description"
                    value={data.description}
                    onChange={(e) => setData((prev) => ({ ...prev, description: e.target.value }))}
                    placeholder="Describe the goal, users, key pages/features, and any constraints."
                    className="min-h-[120px]"
                  />
                </div>
              </div>
            )}

            {step === 3 && (
              <div className="grid gap-4 md:grid-cols-2">
                <div className="grid gap-2">
                  <Label>When do you want it live?</Label>
                  <RadioGroup
                    value={data.timeline}
                    onValueChange={(value) => setData((prev) => ({ ...prev, timeline: value as Timeline }))}
                    className="grid gap-2"
                  >
                    {(['ASAP', '2–4 weeks', '1–2 months', '3–6 months', '6+ months', 'Not sure'] as const).map((value) => (
                      <div key={value} className="flex items-center gap-2">
                        <RadioGroupItem value={value} id={`sp-timeline-${value}`} />
                        <Label htmlFor={`sp-timeline-${value}`} className="font-normal">
                          {value}
                        </Label>
                      </div>
                    ))}
                  </RadioGroup>
                </div>

                <div className="grid gap-4">
                  <div className="grid gap-2">
                    <Label>Currency</Label>
                    <Select
                      value={data.currency}
                      onValueChange={(value) =>
                        setData((prev) => ({
                          ...prev,
                          currency: value as CurrencyCode,
                          budget: '',
                        }))
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select a currency" />
                      </SelectTrigger>
                      <SelectContent className="z-[70]">
                        {CURRENCIES.map((currency) => (
                          <SelectItem key={currency.code} value={currency.code}>
                            {currency.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="grid gap-2">
                    <Label>Budget range</Label>
                    <Select
                      value={data.budget}
                      onValueChange={(value) => setData((prev) => ({ ...prev, budget: value as BudgetRange }))}
                      disabled={!data.currency}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder={data.currency ? 'Select a budget range' : 'Select currency first'} />
                      </SelectTrigger>
                      <SelectContent className="z-[70]">
                        {(CURRENCIES.find((c) => c.code === data.currency)?.ranges ?? []).map((value) => (
                          <SelectItem key={value} value={value}>
                            {value}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="grid gap-2">
                    <Label>Specific go-live date (optional)</Label>
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button
                          variant="outline"
                          className="w-full justify-start border-border/60 bg-transparent text-left font-normal hover:bg-muted"
                        >
                          <CalendarIcon className="mr-2 h-4 w-4" />
                          {data.goLiveDate ? format(new Date(data.goLiveDate), 'PPP') : <span>Pick a date</span>}
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="z-[70] w-auto p-0" align="start">
                        <Calendar
                          mode="single"
                          selected={data.goLiveDate ? new Date(data.goLiveDate) : undefined}
                          onSelect={(date) =>
                            setData((prev) => ({
                              ...prev,
                              goLiveDate: date ? format(date, 'yyyy-MM-dd') : '',
                            }))
                          }
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                  </div>
                </div>
              </div>
            )}

            {step === 4 && (
              <div className="grid gap-4">
                <div className="grid gap-3">
                  <Label>Assets & constraints</Label>
                  <div className="grid gap-3 md:grid-cols-2">
                    {[
                      { key: 'hasBranding', label: 'Branding / logo already exists' },
                      { key: 'hasContent', label: 'Content (copy/images) is ready' },
                      { key: 'hasDomain', label: 'Domain + hosting already exists' },
                      { key: 'needsDesign', label: 'Need design support' },
                    ].map((item) => (
                      <label key={item.key} className="flex items-center gap-3 rounded-lg border border-border/60 bg-background/40 p-3">
                        <Checkbox
                          checked={data[item.key as keyof WizardData] as boolean}
                          onCheckedChange={(checked) =>
                            setData((prev) => ({ ...prev, [item.key]: checked === true }))
                          }
                        />
                        <span className="text-sm text-muted-foreground">{item.label}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <div className="grid gap-2">
                  <Label htmlFor="sp-notes">Anything else we should know? (optional)</Label>
                  <Textarea
                    id="sp-notes"
                    value={data.notes}
                    onChange={(e) => setData((prev) => ({ ...prev, notes: e.target.value }))}
                    placeholder="Links, references, competitors, compliance requirements, etc."
                    className="min-h-[120px]"
                  />
                </div>
              </div>
            )}

            {step === 5 && (
              <div className="grid gap-3">
                <div className="flex items-center justify-between gap-3">
                  <p className="text-sm font-semibold">Review</p>
                  <div className="flex items-center gap-2">
                    <Button type="button" variant="outline" className="border-border/60 bg-transparent hover:bg-muted" onClick={() => copy(summary)}>
                      Copy
                    </Button>
                    <Button asChild className="bg-emerald-500 text-emerald-950 hover:bg-emerald-400">
                      <a href={submitMailtoHref}>
                        Submit via email <Mail className="ml-2 h-4 w-4" />
                      </a>
                    </Button>
                  </div>
                </div>
                <Textarea readOnly value={summary} className="min-h-[240px]" />
                <p className="text-xs text-muted-foreground">
                  This opens your email client with the brief prefilled. Direct in-app submission will be added when the backend/mailing service is implemented.
                </p>
              </div>
            )}

            <div className="mt-2 flex items-center justify-between gap-3">
              <Button
                type="button"
                variant="outline"
                className="border-border/60 bg-transparent hover:bg-muted"
                onClick={() => {
                  if (step === 0) {
                    setConfirmAction('back-to-choice')
                    setConfirmOpen(true)
                  } else {
                    setStep((s) => Math.max(0, s - 1))
                  }
                }}
              >
                Back
              </Button>
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => {
                    setConfirmAction('skip')
                    setConfirmOpen(true)
                  }}
                >
                  Skip wizard
                </Button>
                {step < steps.length - 1 ? (
                  <Button
                    type="button"
                    className="bg-emerald-500 text-emerald-950 hover:bg-emerald-400"
                    disabled={!canNext}
                    onClick={() => setStep((s) => Math.min(steps.length - 1, s + 1))}
                  >
                    Next <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                ) : null}
              </div>
            </div>
          </>
        )}
        </DialogContent>
      </Dialog>

      <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}>
          <AlertDialogContent className="z-[80]">
            <AlertDialogHeader>
            <AlertDialogTitle>
              {confirmAction === 'skip' ? 'Skip the wizard?' : 'Exit the wizard?'}
            </AlertDialogTitle>
            <AlertDialogDescription>
              You’ll lose the guided questions that help create a clear brief. You can still submit details on the contact page.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Continue wizard</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (confirmAction === 'skip') {
                  goContact(false)
                  return
                }
                if (confirmAction === 'back-to-choice') {
                  setMode('choice')
                  return
                }
              }}
            >
              {confirmAction === 'skip' ? 'Yes, skip' : 'Yes, exit'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
